jobs:
  include:
    - language: python
      name: lowe
      python: 3.9
      install:
        - pip install flake8 black --upgrade
      script:
        - cd lowe
        - black --check .
        - flake8 .

    - language: node_js
      name: abernathy
      node_js: 14
      install:
        - npm install --global prettier
      script:
        - cd abernathy
        - prettier --check .
