version: "3.8"

services:
  proxy:
    image: nginx:latest
    container_name: miljomataren_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${PORT}:80"
    expose:
      - "${PORT}"

  lowe:
    image: registry.gitlab.com/vilhelm/miljomataren:lowe
    ports:
      - 5000:5000
    environment:
      # Google Sign-In
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"

      # App url
      BASE_URL: "${BASE_URL}"

      # Database and session
      DATABASE_HOST: "postgresql"
      REDIS_HOST: "redis"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"

      # Since we're running behind proxy, this is OK
      OAUTHLIB_INSECURE_TRANSPORT: "1"
    depends_on:
      - postgresql
      - redis

  abernathy:
    image: registry.gitlab.com/vilhelm/miljomataren:abernathy
    ports:
      - 3000:3000

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: "miljomataren"
      POSTGRES_USER: "miljomataren"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      TZ: "${TIMEZONE}"
      PGTZ: "${TIMEZONE}"
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
