version: "3.8"

services:
  proxy:
    image: nginx:latest
    container_name: miljomataren_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${PORT}:80"
    expose:
      - "${PORT}"

  lowe:
    image: prytz/miljomataren:lowe
    ports: 5000:5000

  abernathy:
    image: prytz/miljomataren:abernathy
    ports: 3000:3000

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: "miljomataren"
      POSTGRES_USER: "miljomataren"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
